# example for ODF storage, for other CSI that will be different
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: kasten-snapshotclass
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
parameters:
  clusterID: openshift-storage
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: openshift-storage
deletionPolicy: Delete
driver: openshift-storage.rbd.csi.ceph.com
