# K10 profile to hook Minio S3 which is local to cluster and located at minio namespace
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: minio-local
  namespace: kasten-io
spec:
  locationSpec:
    objectStore:
      objectStoreType: S3
      name: k10
      region: none
      endpoint: http://minio-service.minio.svc.cluster.local:9000
      skipSSLVerify: false
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: minio-credentials
        namespace: kasten-io
    type: ObjectStore
  type: Location

