apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: '2024-10-13T15:18:51Z'
  generation: 1
  labels:
    operators.coreos.com/k10-kasten-operator-rhmp.kasten-io: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
      time: '2024-10-13T15:18:51Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/k10-kasten-operator-rhmp.kasten-io': {}
      manager: olm
      operation: Update
      time: '2024-10-13T15:18:51Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
      time: '2024-10-13T15:22:31Z'
  name: k10-kasten-operator-rhmp
  namespace: kasten-io
  resourceVersion: '139892'
  uid: bf0933d9-2582-498c-8695-762ff705b13f
spec:
  channel: stable
  installPlanApproval: Automatic
  name: k10-kasten-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: k10-kasten-operator-rhmp.v7.0.11
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-lbfws
    uuid: 53d28e8a-8e50-4b88-8e81-01a1b05797b5
  lastUpdated: '2024-10-13T15:22:31Z'
  installedCSV: k10-kasten-operator-rhmp.v7.0.11
  currentCSV: k10-kasten-operator-rhmp.v7.0.11
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-lbfws
    namespace: kasten-io
    resourceVersion: '136042'
    uid: 53d28e8a-8e50-4b88-8e81-01a1b05797b5
  state: AtLatestKnown
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
        resourceVersion: '135222'
        uid: 7cb2e8db-4a5f-430e-8b68-baeff045f63a
      healthy: true
      lastUpdated: '2024-10-13T15:19:08Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
        resourceVersion: '128802'
        uid: 45c85042-1de1-4fe2-8e9c-6bec6fc5b8e7
      healthy: true
      lastUpdated: '2024-10-13T15:19:08Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-marketplace
        namespace: openshift-marketplace
        resourceVersion: '132465'
        uid: 3e3f4b37-c756-454d-879a-102965ed7169
      healthy: true
      lastUpdated: '2024-10-13T15:19:08Z'
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
        resourceVersion: '132939'
        uid: 8bf6ea56-7221-46aa-b108-ab75c579eb02
      healthy: true
      lastUpdated: '2024-10-13T15:19:08Z'
  conditions:
    - lastTransitionTime: '2024-10-13T15:19:08Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
  installPlanGeneration: 1

